# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box_app', '0003_auto_20170406_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='answercomment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questioncomment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
