# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_box_app', '0004_auto_20170406_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='answercomment',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answercomment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='answervote',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answervote',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questioncomment',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questioncomment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questionvote',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionvote',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
