# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box_app', '0005_auto_20170406_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
