# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_box_app', '0006_auto_20170409_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='answervote',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_box_app.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionvote',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_box_app.Question'),
        ),
    ]
